### PR TITLE
Support for building with Xcode 5 SDK 7.0 (clang).

### PR DESCRIPTION
**Pull request by vasilev**
Fix for #64  to build with Xcode 5 SDK.
Produces a lot of warnings about register sizes while building, but resulting binaries work.

### CODE REVIEW

**Comment by duanhai** [comment]
Can't complie in Xcode 5.1

**Comment by sanghavan** [comment]
You can try to kxmovie at below link (It tested on my Xcode 5.1):
https://www.dropbox.com/s/ubx5dwz2dnmtl8p/kxmovie.zip
I added new .a library of FFmpeg and link to project.

**Comment by duanhai** [comment]
Thank you,can you put the complie script for refference if it's convenient.

------------------ 原始邮件 ------------------
发件人: "sanghavan";notifications@github.com;
发送时间: 2014年4月10日(星期四) 上午10:50
收件人: "kolyvan/kxmovie"kxmovie@noreply.github.com; 
抄送: "大于45°的仰望"duanhai189@qq.com; 
主题: Re: [kxmovie] Support for building with Xcode 5 SDK 7.0 (clang).(#66)

You can try on kxmovie at below link (It tested on my Xcode 5.1):
https://www.dropbox.com/s/ubx5dwz2dnmtl8p/kxmovie.zip
 I added new .a library of FFmpeg and link to project.

**Comment by sanghavan** [comment]
When you clone kxmovie project at github, it missing .a files of FFmpeg library. So you need add those missing files.
Step 1:
You can build the .a files with guideline and script at https://github.com/kewlbear/FFmpeg-iOS-build-script/
or
Download .a files at https://github.com/kewlbear/FFmpeg-iOS-build-script/#download

Step 2:
Import .a missing files to project.

Step 3:
Go to Target at project setting -> Build Setting - > Library Search Paths, paste path to folder contain .a files.

Step 4: 
Go to Build Setting - > Header Search Paths,  paste path to folder contain .h files.

Notes: Don't need link .h file to project by drag and drop or add new file.

**Pull request closed without merging**
