### PR TITLE
Build FFmpeg from release/1.1 tag

### PR DESCRIPTION
**Pull request by kristopherjohnson**
This branch updates the FFmpeg submodule to use the latest commit in the release/1.1 branch, and updates Rakefile, gas-preprocessor.pl, and the KxMovieExample project to build correctly with those sources.

See https://github.com/kolyvan/kxmovie/issues/25 for more details about what was changed and why.

### CODE REVIEW

**Comment by kolyvan** [comment]
Hi, 
First, thanks for your great work.

Today I downloaded  and examined your path.
So I have some questions / remarks.
1. linking with libiconv. Why is it necessary? 
2. It seems the support of mpeg1 and mpeg2 was broken by ffmpeg 1.1. 

the links for mpeg1/mpeg2 movies:
http://dl.dropbox.com/u/80472203/video_test/Beyonce%20-%20Run%20the%20world%20(Girls).VOB
http://dl.dropbox.com/u/80472203/video_test/X2%20Double%20X.mpg 

You may play these movies on simulator but problem arisen on device.
1. Interesting what with h264 there is opposite situation.
   No problems on the device but on the simulator is noisy video.

test links:
http://www.dvdloc8.com/clip.php?movieid=12167&clipid=1
http://www.dvdloc8.com/clip.php?movieid=13006&clipid=1
1. The annoying warnings: 'ARM function not 4-byte aligned'

Perhaps, ffmpeg 1.1 is not yet stable and not ready for using.
Or maybe need to tune of configure options.

Best wishes.

**Comment by kolyvan** [comment]
> Interesting what with h264 there is opposite situation.
> No problems on the device but on the simulator is noisy video.

If add --disable-inline-asm or --disable-asm flags to FFMPEG_BUILD_ARGS_SIM options, it will solve simulator h264 issue.

**Comment by kolyvan** [comment]
The adding of flag '--disable-asm' also solves issue with broken mpeg1/2 on device.
IMHO the problem in lastest changes of  gas-preprocessor.pl.

**Comment by kristopherjohnson** [comment]
I added libiconv when I had some linking errors with symbols starting with _iconv. I didn't do any investigation to determine why that changed. However, that was before I updated gas_preprocessor.pl, so maybe that's not necessary anymore?

With my app, which displays video from Axis CCTV cameras, the ffmpeg 1.1 version seems to be more stable than the previous version. We had frequent crashes in the H.264 decoder with the old FFmpeg, but those don't happen with the new version. I didn't test with other video streams.

Everything I've found online indicates that the "ARM function not 4-byte aligned" warnings are harmless. It would be nice to get rid of them.

I'll try your suggested changes to configure options.

**Comment by kristopherjohnson** [comment]
I've updated my branch to use the 1.1.3 release of FFmpeg, and added the --disable-asm flag to the configuration options.

This is working well with the video feeds I'm using, both in simulator and on device.

**Comment by bezigon** [comment]
I've used latest code of FFmpeg release/1.1 branch and noticed that there are (un-)locking problems (codec?) while fast dealloc'ing and opening new instance of KxMovieViewController.

I will try checking the n1.1.3 tag of FFmpeg.

**Comment by kolyvan** [comment]
I commited 7b77b0fa869e6fb3138458e3dddb27cf668acebd with next main changes:
- use ffmpeg release/1.2
- add --enable-small flag to configs

And It seems it solves mpeg1/2 issues.

**Comment by alexGDdev** [comment]
`--disable-asm` Also solved some problems with MMS streams on device.

**Pull request closed without merging**
